version: '3.0'

services:
    kali:
        hostname: kali-docker
        build: .
        ports:
            - "6080:80"
            - "6022:22"
        volumes:
            - <your_disk>:/srv
        privileged: true
        tty: true
        cap_add:
            - NET_ADMIN
        devices:
            - /dev/net/tun:/dev/net/tun
        network_mode: bridge
        environment:
            - OPENVPN_OPTS=--pull-filter ignore "ifconfig-ipv6";--pull-filter ignore "route-ipv6"
            - VNC_PASSWORD=<your_password>
        sysctls:
            - net.ipv6.conf.all.disable_ipv6=0
